// Auto-generated list of allowed Apify contact_location values
export const ALLOWED_LOCATIONS: Set<string> = new Set([
  'aargau, switzerland',
  'abruzzo, italy',
  'abu dhabi, united arab emirates',
  'aceh, indonesia',
  'acre, brazil',
  'adamawa, nigeria',
  'adana, turkey',
  'addis ababa, ethiopia',
  'adjuntas, puerto rico',
  'adygea, russia',
  'afghanistan',
  'agadez, niger',
  'aguadilla, puerto rico',
  'aguascalientes, mexico',
  'ahmadi, kuwait',
  'aichi prefecture, japan',
  'aichi-ken, japan',
  'ajman, united arab emirates',
  'akershus, norway',
  'akita prefecture, japan',
  'aksaray, turkey',
  'akwa ibom, nigeria',
  'al asimah, kuwait',
  'al bahah province, saudi arabia',
  'al batinah north governorate, oman',
  'al khor, qatar',
  'al madinah province, saudi arabia',
  'al qalyubia governorate, egypt',
  'al wakrah, qatar',
  'alabama, us',
  'alagoas, brazil',
  'alajuela, costa rica',
  'aland islands',
  'alaska, us',
  'alba county, romania',
  'albania',
  'alberta, canada',
  'alexandria governorate, egypt',
  'alger, algeria',
  'algeria',
  'algiers, algeria',
  'almaty region, kazakhstan',
  'alsace, france',
  'alsace-champagne-ardenne-lorraine, france',
  'alta verapaz, guatemala',
  'altai krai, russia',
  'altai republic, russia',
  'altayskiy kray, russia',
  'amapá, brazil',
  'amazonas department, colombia',
  'amazonas, brazil',
  'amazonas, colombia',
  'amman governorate, jordan',
  'amman, jordan',
  'amur oblast, russia',
  'amurskaya oblast\', russia',
  'anambra, nigeria',
  'ancash, peru',
  'andalucía, spain',
  'andalusia, spain',
  'andhra pradesh, india',
  'andijan province, uzbekistan',
  'andorra',
  'angola',
  'anguilla',
  'anhui, china',
  'ankara province, turkey',
  'antioquia, colombia',
  'antofagasta region, chile',
  'anzoategui, venezuela',
  'aomori prefecture, japan',
  'appenzell innerrhoden, switzerland',
  'appenzell outer rhodes, switzerland',
  'apulia, italy',
  'apurimac, peru',
  'aquitaine, france',
  'aquitaine-limousin-poitou-charentes, france',
  'arad county, romania',
  'aragon, spain',
  'aragua, venezuela',
  'aragón, spain',
  'arauca, colombia',
  'arequipa, peru',
  'argentina',
  'argeș county, romania',
  'ariana, tunisia',
  'arizona, us',
  'arkansas, us',
  'arkhangelsk oblast, russia',
  'arkhangelskaya oblast\', russia',
  'armenia',
  'arusha, tanzania',
  'aseer province, saudi arabia',
  'ash sharqia governorate, egypt',
  'ash sharqiyah north governorate, oman',
  'ashanti, ghana',
  'assam, india',
  'astrakhan oblast, russia',
  'astrakhanskaya oblast\', russia',
  'asturias, spain',
  'atlantico, colombia',
  'atlántico, colombia',
  'attica, greece',
  'atyrau region, kazakhstan',
  'auckland, new zealand',
  'aust-agder, norway',
  'australia',
  'australian capital territory, australia',
  'austria',
  'autonomous city of buenos aires, argentina',
  'auvergne, france',
  'auvergne-rhône-alpes, france',
  'aveiro district, portugal',
  'ayacucho, peru',
  'aydın province, turkey',
  'azerbaijan',
  'azores, portugal',
  'azuay, ecuador',
  'açores, portugal',
  'añasco, puerto rico',
  'ba ria - vung tau, vietnam',
  'bacău county, romania',
  'baden-württemberg, germany',
  'baghdād, iraq',
  'bahia, brazil',
  'bahrain',
  'baja california sur, mexico',
  'baja california, mexico',
  'balearic islands, spain',
  'bali, indonesia',
  'balkh, afghanistan',
  'balochistan, pakistan',
  'balıkesir province, turkey',
  'balıkesir, turkey',
  'bamako, mali',
  'bangkok, thailand',
  'bangladesh',
  'banská bystrica region, slovakia',
  'banten, indonesia',
  'banten, republic of indonesia',
  'baranya, hungary',
  'barbados',
  'barinas, venezuela',
  'basel-landschaft, switzerland',
  'basel-stadt, switzerland',
  'basilicata, italy',
  'basque country, spain',
  'basrah, iraq',
  'basse-terre, guadeloupe',
  'battambang, cambodia',
  'bauchi, nigeria',
  'bavaria, germany',
  'bay of plenty, new zealand',
  'bayamón, puerto rico',
  'bayburt, turkey',
  'bayern, germany',
  'beijing shi, china',
  'beijing, china',
  'beirut, lebanon',
  'beja district, portugal',
  'beja, portugal',
  'belarus',
  'belgium',
  'belgorod oblast, russia',
  'belgorodskaya oblast\', russia',
  'belize',
  'bengkulu, indonesia',
  'beni department, bolivia',
  'beni, bolivia',
  'benin',
  'berlin, germany',
  'bermuda',
  'bern, switzerland',
  'bhutan',
  'bicol, philippines',
  'bihar, india',
  'bihor county, romania',
  'bingöl province, turkey',
  'bingöl, turkey',
  'binh dinh province, vietnam',
  'binh thuan, vietnam',
  'bio-bio, chile',
  'bioko norte, equatorial guinea',
  'biskra, algeria',
  'bistrița-năsăud county, romania',
  'bitlis, turkey',
  'blagoevgrad province, bulgaria',
  'blekinge county, sweden',
  'bogota, colombia',
  'bolivar, colombia',
  'bolivia',
  'bolívar, colombia',
  'bolívar, venezuela',
  'bonaire, bonaire, sint eustatius and saba',
  'bonaire, sint eustatius and saba',
  'borno, nigeria',
  'borsod-abaúj-zemplén, hungary',
  'bosnia and herzegovina',
  'botoșani county, romania',
  'botswana',
  'bourgogne franche-comté, france',
  'bourgogne, france',
  'bourgogne-franche-comté, france',
  'boyaca, colombia',
  'boyacá, colombia',
  'braga, portugal',
  'bragança district, portugal',
  'bragança, portugal',
  'brandenburg, germany',
  'bratislava region, slovakia',
  'brazil',
  'brașov county, romania',
  'bremen, germany',
  'bretagne, france',
  'british columbia, canada',
  'brittany, france',
  'brong ahafo, ghana',
  'brunei',
  'brunei-muara, brunei',
  'brussel, belgium',
  'brussels hoofdstedelijk gewest, belgium',
  'brussels, belgium',
  'bruxelles, belgium',
  'bryansk oblast, russia',
  'bryanskaya oblast\', russia',
  'brăila county, romania',
  'bucharest, romania',
  'budapest, hungary',
  'bueng kan, thailand',
  'buenos aires province, argentina',
  'bujumbura mairie, burundi',
  'bulgaria',
  'burdur, turkey',
  'burgandy, france',
  'burgas, bulgaria',
  'burgenland, austria',
  'burgundy, france',
  'burkina faso',
  'bursa, turkey',
  'burundi',
  'buryatia, russia',
  'buryatiya republits, russia',
  'buskerud, norway',
  'buzău county, romania',
  'bà rịa - vũng tàu, vietnam',
  'bács-kiskun, hungary',
  'békés county, hungary',
  'bình dương, vietnam',
  'bình phước, vietnam',
  'bío bío region, chile',
  'bạc liêu, vietnam',
  'cabo delgado, mozambique',
  'cabo rojo, puerto rico',
  'cagayan valley, philippines',
  'caguas, puerto rico',
  'cairo governorate, egypt',
  'cajamarca, peru',
  'calabarzon, colombia',
  'calabarzon, philippines',
  'calabria, italy',
  'caldas, colombia',
  'california, us',
  'cambodia',
  'cameroon',
  'campania, italy',
  'campeche, mexico',
  'canada',
  'canarias, spain',
  'canary islands, spain',
  'canelones, uruguay',
  'cantabria, spain',
  'canterbury, new zealand',
  'canton of bern, switzerland',
  'canton of fribourg, switzerland',
  'canton of glarus, switzerland',
  'canton of jura, switzerland',
  'canton of neuchâtel, switzerland',
  'canton of obwalden, switzerland',
  'canton of schaffhausen, switzerland',
  'canton of schwyz, switzerland',
  'canton of solothurn, switzerland',
  'canton of uri, switzerland',
  'canton of zug, switzerland',
  'canóvanas, puerto rico',
  'capital district, venezuela',
  'capital governorate, bahrain',
  'capital region of denmark, denmark',
  'capital region, iceland',
  'caquetá, colombia',
  'carabobo, venezuela',
  'caracas metropolitan district, venezuela',
  'caraga, philippines',
  'caraș-severin county, romania',
  'carinthia, austria',
  'carlow, ireland',
  'carolina, puerto rico',
  'cartago, costa rica',
  'casanare, colombia',
  'castelo branco district, portugal',
  'castile and león, spain',
  'castile-la mancha, spain',
  'castilla y león, spain',
  'castilla-la mancha, spain',
  'catalonia, spain',
  'catalunya, spain',
  'cataluña, spain',
  'catamarca province, argentina',
  'cauca department, colombia',
  'cavan, ireland',
  'cayenne, french guiana',
  'cayey, puerto rico',
  'cayman islands',
  'ceará, brazil',
  'ceiba, puerto rico',
  'center district, israel',
  'central african republic',
  'central bohemian region, czech republic',
  'central denmark region, denmark',
  'central division, fiji',
  'central finland, finland',
  'central governorate, bahrain',
  'central java, indonesia',
  'central java, republic of indonesia',
  'central kalimantan, indonesia',
  'central luzon, philippines',
  'central region, nepal',
  'central region, uganda',
  'central sulawesi, indonesia',
  'central visayas, philippines',
  'central, ghana',
  'centre, france',
  'centre-val de loire, france',
  'cesar, colombia',
  'ceuta, spain',
  'chachoengsao, thailand',
  'chaco province, argentina',
  'chad',
  'chai nat, thailand',
  'champagne-ardenne, france',
  'chandigarh, india',
  'chang wat chachoengsao, thailand',
  'chang wat nakhon pathom, thailand',
  'chechenskaya republits, russia',
  'chechnya, russia',
  'chelyabinsk oblast, russia',
  'chelyabinskaya oblast\', russia',
  'cherkas\'ka oblast, ukraine',
  'chernihivs\'ka oblast, ukraine',
  'chernivets\'ka oblast, ukraine',
  'chhattisgarh, india',
  'chiang rai, thailand',
  'chiapas, mexico',
  'chiba prefecture, japan',
  'chihuahua, mexico',
  'chile',
  'chimborazo, ecuador',
  'china',
  'chisinau, moldova',
  'choco, colombia',
  'chocó, colombia',
  'chon buri, thailand',
  'chongqing shi, china',
  'chongqing, china',
  'chubut province, argentina',
  'chukotka autonomous okrug, russia',
  'chungcheongbuk-do, south korea',
  'chungcheongnam-do, south korea',
  'chuvashia republic, russia',
  'chuvashia, russia',
  'chuy province, kyrgyzstan',
  'cidra, puerto rico',
  'city of zagreb, croatia',
  'ciudad autónoma de buenos aires, argentina',
  'ciudad de méxico, mexico',
  'clare, ireland',
  'cluj county, romania',
  'coahuila de zaragoza, mexico',
  'coahuila, mexico',
  'cochabamba department, bolivia',
  'coimbra district, portugal',
  'colima, mexico',
  'colombia',
  'colonia, uruguay',
  'colorado, us',
  'community of madrid, spain',
  'comunidad de madrid, spain',
  'comunidad valenciana, spain',
  'comunitat valenciana, spain',
  'connecticut, us',
  'constantine, algeria',
  'constanța county, romania',
  'cook islands',
  'copperbelt, zambia',
  'coquimbo region, chile',
  'cordillera administrative region, philippines',
  'cordoba, argentina',
  'cordoba, colombia',
  'cork, ireland',
  'corrientes province, argentina',
  'corsica, france',
  'costa rica',
  'covasna county, romania',
  'crete, greece',
  'croatia',
  'cross river, nigeria',
  'csongrád, hungary',
  'cuba',
  'cundinamarca, colombia',
  'cusco, peru',
  'cuzco, peru',
  'cymru, united kingdom',
  'cyprus',
  'czech republic',
  'côte d\'ivoire',
  'călărași county, romania',
  'cần thơ, vietnam',
  'da nang, vietnam',
  'dadra and nagar haveli, india',
  'dagestan republic, russia',
  'dagestan republits, russia',
  'dakar, senegal',
  'dalarna county, sweden',
  'daman and diu, india',
  'damascus governorate, syria',
  'damietta governorate, egypt',
  'davao region, philippines',
  'delaware, us',
  'delhi, india',
  'delta, nigeria',
  'democratic republic of the congo',
  'denizli, turkey',
  'denmark',
  'departamento autónomo de oruro, bolivia',
  'departamento de lima, peru',
  'dhaka division, bangladesh',
  'district of columbia, us',
  'distrito capital, venezuela',
  'distrito de beja, portugal',
  'distrito de évora, portugal',
  'distrito federal, brazil',
  'distrito federal, mexico',
  'distrito metropolitano de caracas, venezuela',
  'diyarbakır, turkey',
  'dnipropetrovsk oblast, ukraine',
  'dobrich province, bulgaria',
  'doha, qatar',
  'dolj county, romania',
  'dominica',
  'dominican republic',
  'donegal, ireland',
  'donetsk oblast, ukraine',
  'dong nai, vietnam',
  'dorado, puerto rico',
  'doukkala-abda, morocco',
  'drenthe, netherlands',
  'dubai, united arab emirates',
  'dublin, ireland',
  'durango, mexico',
  'dzhalal-abadskaya, kyrgyzstan',
  'dâmbovița county, romania',
  'east java, indonesia',
  'east java, republic of indonesia',
  'east kalimantan, indonesia',
  'east kazakhstan region, kazakhstan',
  'east nusa tenggara, indonesia',
  'eastern cape, south africa',
  'eastern province, saudi arabia',
  'eastern region, uganda',
  'eastern, ghana',
  'ecuador',
  'edirne, turkey',
  'edo, nigeria',
  'egeo, greece',
  'egypt',
  'ehime prefecture, japan',
  'el salvador',
  'emilia-romagna, italy',
  'enga province, papua new guinea',
  'england, united kingdom',
  'entre rios, argentina',
  'enugu, nigeria',
  'equatorial guinea',
  'erbil, iraq',
  'erzincan, turkey',
  'erzurum, turkey',
  'eskişehir province, turkey',
  'espírito santo, brazil',
  'estado de méxico, mexico',
  'estonia',
  'estuaire, gabon',
  'ethiopia',
  'euskadi, spain',
  'extremadura, spain',
  'fajardo, puerto rico',
  'falkland islands (islas malvinas)',
  'faro district, portugal',
  'faryab, afghanistan',
  'federal capital territory, nigeria',
  'federal district, brazil',
  'federal district, mexico',
  'federal territory of kuala lumpur, malaysia',
  'federation of bosnia and herzegovina, bosnia and herzegovina',
  'fejér, hungary',
  'fes-boulemane, morocco',
  'fiji',
  'finland',
  'finnmark, norway',
  'flanders, belgium',
  'flevoland, netherlands',
  'florida, us',
  'formosa province, argentina',
  'fort-de-france, martinique',
  'fr, italy',
  'france',
  'franche-comté, france',
  'francisco morazan, honduras',
  'free state, south africa',
  'freeport, the bahamas',
  'freiburg, switzerland',
  'french guiana',
  'french polynesia',
  'friesland, netherlands',
  'friuli-venezia giulia, italy',
  'fujairah, united arab emirates',
  'fujian, china',
  'fukui prefecture, japan',
  'fukuoka prefecture, japan',
  'fukushima prefecture, japan',
  'fukushima-ken, japan',
  'gabon',
  'gabrovo, bulgaria',
  'galați, romania',
  'galicia, spain',
  'galway, ireland',
  'gambella, ethiopia',
  'gangwon-do, south korea',
  'gansu, china',
  'gauteng, south africa',
  'gavleborg county, sweden',
  'gaziantep, turkey',
  'gelderland, netherlands',
  'geneva, switzerland',
  'genève, switzerland',
  'georgia',
  'georgia, us',
  'germany',
  'ghana',
  'gharb-chrarda-beni hssen, morocco',
  'gia lai province, vietnam',
  'gibraltar',
  'gifu prefecture, japan',
  'gisborne, new zealand',
  'giurgiu county, romania',
  'giza governorate, egypt',
  'glarus, switzerland',
  'goa, india',
  'goiás, brazil',
  'gombe, nigeria',
  'gorj county, romania',
  'gorod moskva, russia',
  'gorod sankt-peterburg, russia',
  'gorontalo, indonesia',
  'gotland county, sweden',
  'gouvernorat de tunis, tunisia',
  'grand casablanca, morocco',
  'grande-terre, guadeloupe',
  'granma, cuba',
  'graubünden, switzerland',
  'greater accra, ghana',
  'greater poland voivodeship, poland',
  'greece',
  'greenland',
  'grisons, switzerland',
  'grodno region, belarus',
  'groningen, netherlands',
  'guadeloupe',
  'guainia, colombia',
  'guam',
  'guam, us',
  'guanacaste, costa rica',
  'guanajuato, mexico',
  'guangdong sheng, china',
  'guangdong, china',
  'guangxi, china',
  'guarda district, portugal',
  'guatemala',
  'guatemala, guatemala',
  'guayama, puerto rico',
  'guayas, ecuador',
  'guaynabo, puerto rico',
  'guernsey',
  'guerrero, mexico',
  'guizhou, china',
  'gujarat, india',
  'gunma prefecture, japan',
  'gurabo, puerto rico',
  'guyana',
  'guárico, venezuela',
  'gwangju, south korea',
  'gyeonggi-do, south korea',
  'gyeongsangbuk-do, south korea',
  'gyeongsangnam-do, south korea',
  'gyõr-moson-sopron, hungary',
  'gümüşhane, turkey',
  'habaka, jordan',
  'hai duong, vietnam',
  'haifa district, israel',
  'hainan, china',
  'haiphong, vietnam',
  'haiti',
  'hajdú-bihar, hungary',
  'halland county, sweden',
  'hamburg, germany',
  'hamilton, bermuda',
  'hanoi, vietnam',
  'harghita county, romania',
  'harju county, estonia',
  'haryana, india',
  'haskovo province, bulgaria',
  'hatay province, turkey',
  'hatay, turkey',
  'hatillo, puerto rico',
  'hato mayor, dominican republic',
  'haute-normandie, france',
  'hawaii, us',
  'hawally governorate, kuwait',
  'hawke\'s bay, new zealand',
  'hebei, china',
  'hedmark, norway',
  'heilongjiang, china',
  'henan sheng, china',
  'henan, china',
  'herat, afghanistan',
  'heredia province, costa rica',
  'hesse, germany',
  'hessen, germany',
  'heves county, hungary',
  'hhohho, swaziland',
  'hidalgo, mexico',
  'himachal pradesh, india',
  'hiroshima prefecture, japan',
  'hlavní město praha, czech republic',
  'ho chi minh, vietnam',
  'hokkaido prefecture, japan',
  'honduras',
  'hong kong',
  'hong kong island, hong kong',
  'hordaland, norway',
  'hormigueros, puerto rico',
  'hradec králové region, czech republic',
  'huambo, angola',
  'huancavelica, peru',
  'huanuco, peru',
  'hubei, china',
  'huila, colombia',
  'humacao, puerto rico',
  'hunan, china',
  'hunedoara county, romania',
  'hungary',
  'huíla, angola',
  'hyogo prefecture, japan',
  'hà giang, vietnam',
  'hòa bình, vietnam',
  'hồ chí minh, vietnam',
  'ialomița county, romania',
  'iași county, romania',
  'ibaraki prefecture, japan',
  'ica, peru',
  'iceland',
  'idaho, us',
  'ilfov county, romania',
  'illes balears, spain',
  'illinois, us',
  'ilocos region, philippines',
  'imbabura, ecuador',
  'imo, nigeria',
  'india',
  'indiana, us',
  'indonesia',
  'ingushetia, russia',
  'ingushetiya republits, russia',
  'inner mongolia, china',
  'iowa, us',
  'ipiros ditiki makedonia, greece',
  'iran',
  'iraq',
  'ireland',
  'irkutsk oblast, russia',
  'irkutskaya oblast\', russia',
  'ishikawa prefecture, japan',
  'islamabad capital territory, pakistan',
  'isle of man',
  'isparta, turkey',
  'israel',
  'istria county, croatia',
  'italy',
  'ivano-frankivs\'ka oblast, ukraine',
  'ivanovo oblast, russia',
  'ivanovskaya oblast\', russia',
  'iwate prefecture, japan',
  'i̇stanbul province, turkey',
  'jakarta, indonesia',
  'jalisco, mexico',
  'jamaica',
  'jambi, indonesia',
  'jambol, bulgaria',
  'jamtland county, sweden',
  'japan',
  'jawa barat, indonesia',
  'jawa tengah, indonesia',
  'jayuya, puerto rico',
  'jazan, saudi arabia',
  'jeju-do, south korea',
  'jeollabuk-do, south korea',
  'jeollanam-do, south korea',
  'jersey',
  'jerusalem district, israel',
  'jewish autonomous oblast, russia',
  'jharkhand, india',
  'jiangsu, china',
  'jiangxi, china',
  'jigawa, nigeria',
  'jilin sheng, china',
  'jilin, china',
  'johor, malaysia',
  'jonkoping county, sweden',
  'jordan',
  'juana díaz, puerto rico',
  'județul alba, romania',
  'județul arad, romania',
  'județul argeș, romania',
  'județul bihor, romania',
  'județul cluj, romania',
  'județul constanța, romania',
  'județul dolj, romania',
  'județul dâmbovița, romania',
  'județul galați, romania',
  'județul hunedoara, romania',
  'județul ialomița, romania',
  'județul iași, romania',
  'județul maramureș, romania',
  'județul mureș, romania',
  'județul neamț, romania',
  'județul prahova, romania',
  'județul sibiu, romania',
  'județul suceava, romania',
  'județul sălaj, romania',
  'județul timiș, romania',
  'județul vâlcea, romania',
  'jujuy, argentina',
  'junin, peru',
  'jász-nagykun-szolnok, hungary',
  'kabardino-balkaria, russia',
  'kabul, afghanistan',
  'kaduna, nigeria',
  'kagawa prefecture, japan',
  'kagoshima prefecture, japan',
  'kalasin, thailand',
  'kaliningrad oblast, russia',
  'kaliningradskaya oblast\', russia',
  'kalmar county, sweden',
  'kalmykia, russia',
  'kaluga oblast, russia',
  'kaluzhskaya oblast\', russia',
  'kamchatka krai, russia',
  'kamchatskiy kray, russia',
  'kampong cham, cambodia',
  'kanagawa prefecture, japan',
  'kanchanaburi, thailand',
  'kandahar, afghanistan',
  'kano, nigeria',
  'kansas, us',
  'karachay-cherkessia, russia',
  'kardzhali province, bulgaria',
  'kareliya republits, russia',
  'karlovy vary region, czech republic',
  'karnataka, india',
  'kashkadarya province, uzbekistan',
  'kastamonu, turkey',
  'katsina, nigeria',
  'kaunas county, lithuania',
  'kayseri province, turkey',
  'kazakhstan',
  'kedah, malaysia',
  'kef, tunisia',
  'kelantan, malaysia',
  'kemerovo oblast, russia',
  'kemerovskaya oblast\', russia',
  'kentucky, us',
  'kenya',
  'kerala, india',
  'kerry, ireland',
  'khabarovsk krai, russia',
  'khabarovskiy kray, russia',
  'khakasiya republits, russia',
  'khanty-mansi autonomous okrug, russia',
  'khanty-mansiyskiy avtonomnyy okrug, russia',
  'kharkiv oblast, ukraine',
  'khartoum, sudan',
  'khersons\'ka oblast, ukraine',
  'khmel\'nyts\'ka oblast, ukraine',
  'khon kaen, thailand',
  'khulna division, bangladesh',
  'khyber pakhtunkhwa, pakistan',
  'khánh hòa, vietnam',
  'kiambu, kenya',
  'kien giang, vietnam',
  'kigali, rwanda',
  'kigoma, tanzania',
  'kildare, ireland',
  'kilkenny, ireland',
  'kinshasa, democratic republic of the congo',
  'kiribati',
  'kirov oblast, russia',
  'kirovohrads\'ka oblast, ukraine',
  'kirovskaya oblast\', russia',
  'kisumu, kenya',
  'klaipėda county, lithuania',
  'kocaeli, turkey',
  'kochi prefecture, japan',
  'kogi, nigeria',
  'komi republic, russia',
  'komi republits, russia',
  'komárom-esztergom, hungary',
  'konya province, turkey',
  'konya, turkey',
  'kosovo',
  'kostroma oblast, russia',
  'kostromskaya oblast\', russia',
  'kouilou, republic of the congo',
  'koungou, mayotte',
  'kowloon, hong kong',
  'košice region, slovakia',
  'krasnodar krai, russia',
  'krasnodarskiy kray, russia',
  'krasnoyarsk krai, russia',
  'krasnoyarskiy kray, russia',
  'kronoberg county, sweden',
  'krung thep maha nakhon, thailand',
  'kujawsko-pomorskie, poland',
  'kumamoto prefecture, japan',
  'kunar, afghanistan',
  'kurdistan region, iraq',
  'kurgan oblast, russia',
  'kurganskaya oblast\', russia',
  'kursk oblast, russia',
  'kurskaya oblast\', russia',
  'kuwait',
  'kuyavian-pomeranian voivodeship, poland',
  'kwara, nigeria',
  'kwazulu-natal, south africa',
  'kyiv city, ukraine',
  'kyivs\'ka oblast, ukraine',
  'kymenlaakso, finland',
  'kyoto prefecture, japan',
  'kyrgyzstan',
  'kyustendil province, bulgaria',
  'kyustendil, bulgaria',
  'kärnten, austria',
  'kütahya, turkey',
  'kırklareli, turkey',
  'kırşehir, turkey',
  'la guajira, colombia',
  'la libertad, peru',
  'la pampa province, argentina',
  'la paz department, bolivia',
  'la rioja province, argentina',
  'la rioja, spain',
  'la romana, dominican republic',
  'la vega, dominican republic',
  'lacs, côte d\'ivoire',
  'lagos, nigeria',
  'lagunes, côte d\'ivoire',
  'laikipia, kenya',
  'lambayeque, peru',
  'lampung, indonesia',
  'land salzburg, austria',
  'lang son province, vietnam',
  'languedoc-roussillon midi-pyrénées, france',
  'languedoc-roussillon, france',
  'languedoc-roussillon-midi-pyrénées, france',
  'laois, ireland',
  'laos',
  'lapland, finland',
  'lara, venezuela',
  'latvia',
  'lazio, italy',
  'le marin, martinique',
  'lebanon',
  'leiria district, portugal',
  'leitrim, ireland',
  'leningrad oblast, russia',
  'leningradskaya oblast\', russia',
  'lesotho',
  'lesser poland voivodeship, poland',
  'liaoning sheng, china',
  'liaoning, china',
  'liberec region, czech republic',
  'liberia',
  'libya',
  'liechtenstein',
  'liguria, italy',
  'lima region, peru',
  'lima, peru',
  'limassol, cyprus',
  'limburg, netherlands',
  'limerick, ireland',
  'limon, costa rica',
  'limousin, france',
  'limpopo, south africa',
  'limón, costa rica',
  'lipetsk oblast, russia',
  'lipetskaya oblast\', russia',
  'lisboa, portugal',
  'lisbon, portugal',
  'lithuania',
  'ljubljana, slovenia',
  'lombardia, italy',
  'lombardy, italy',
  'long an, vietnam',
  'lorraine, france',
  'los lagos region, chile',
  'los ríos region, chile',
  'louisiana, us',
  'louth, ireland',
  'lovec, bulgaria',
  'lower austria, austria',
  'lower normandy, france',
  'lower saxony, germany',
  'lower silesian voivodeship, poland',
  'loíza, puerto rico',
  'luanda, angola',
  'lubelskie, poland',
  'lublin voivodeship, poland',
  'lubuskie, poland',
  'lubusz voivodeship, poland',
  'lucerne, switzerland',
  'luhans\'ka oblast, ukraine',
  'luquillo, puerto rico',
  'lusaka, zambia',
  'luxembourg',
  'luxembourg, luxembourg',
  'luzern, switzerland',
  'lviv oblast, ukraine',
  'lâm đồng, vietnam',
  'macau',
  'macedonia (fyrom)',
  'madagascar',
  'madeira, portugal',
  'madhya pradesh, india',
  'madre de dios, peru',
  'magadan oblast, russia',
  'magallanes y la antártica chilena region, chile',
  'magdalena, colombia',
  'maharashtra, india',
  'maine, us',
  'makedonia thraki, greece',
  'makkah province, saudi arabia',
  'malacca, malaysia',
  'malatya, turkey',
  'malawi',
  'malaysia',
  'maldives',
  'maldonado, uruguay',
  'mali',
  'malta',
  'maluku, indonesia',
  'managua, nicaragua',
  'manawatu-wanganui, new zealand',
  'manisa, turkey',
  'manitoba, canada',
  'manyara, tanzania',
  'maputo city, mozambique',
  'maramureș county, romania',
  'maranhão, brazil',
  'marche, italy',
  'mardin, turkey',
  'mari el republic, russia',
  'maritime, togo',
  'marlborough, new zealand',
  'marrakech-tensift-al haouz, morocco',
  'marrakesh-tensift-el haouz, morocco',
  'martinique',
  'maryland, us',
  'maría trinidad sánchez, dominican republic',
  'maseru, lesotho',
  'masovian voivodeship, poland',
  'massachusetts, us',
  'mato grosso do sul, brazil',
  'mato grosso do sul, paraguay',
  'mato grosso, brazil',
  'mauritania',
  'mauritius',
  'mayagüez, puerto rico',
  'mayo, ireland',
  'mayotte',
  'mazowieckie, poland',
  'małopolskie, poland',
  'meath, ireland',
  'mecklenburg-vorpommern, germany',
  'mehedinți county, romania',
  'melilla, spain',
  'mendoza province, argentina',
  'menia governorate, egypt',
  'menofia governorate, egypt',
  'meta, colombia',
  'metro manila, philippines',
  'mexico',
  'mexico city, mexico',
  'michigan, us',
  'michoacán, mexico',
  'midi-pyrénées, france',
  'mie prefecture, japan',
  'minas gerais, brazil',
  'minnesota, us',
  'minsk region, belarus',
  'miranda, venezuela',
  'misiones province, argentina',
  'mississippi, us',
  'missouri, us',
  'miyagi prefecture, japan',
  'miyazaki prefecture, japan',
  'mizoram, india',
  'mjini magharibi, tanzania',
  'moldova',
  'molise, italy',
  'mombasa, kenya',
  'monaco',
  'monagas, venezuela',
  'monaghan, ireland',
  'mongolia',
  'montana province, bulgaria',
  'montana, us',
  'montenegro',
  'montevideo department, uruguay',
  'montserrado, liberia',
  'mopti, mali',
  'moquegua, peru',
  'moravian-silesian region, czech republic',
  'mordovia, russia',
  'morocco',
  'moscow oblast, russia',
  'moscow, russia',
  'moskovskaya oblast\', russia',
  'mostaganem, algeria',
  'mozambique',
  'mugla, turkey',
  'municipiul bucurești, romania',
  'muramvya, burundi',
  'mureș county, romania',
  'murmansk oblast, russia',
  'murmanskaya oblast\', russia',
  'muscat governorate, oman',
  'muğla province, turkey',
  'mwanza, tanzania',
  'myanmar',
  'myanmar (burma)',
  'mykolaivs\'ka oblast, ukraine',
  'mérida, venezuela',
  'møre og romsdal, norway',
  'nagaland, india',
  'nagano prefecture, japan',
  'nagasaki prefecture, japan',
  'naguabo, puerto rico',
  'nairobi, kenya',
  'najran, saudi arabia',
  'nakhon nayok, thailand',
  'nakhon pathom, thailand',
  'nakhon sawan, thailand',
  'nakhon si thammarat, thailand',
  'nakuru, kenya',
  'nam dinh, vietnam',
  'namibia',
  'nampula, mozambique',
  'nangarhar, afghanistan',
  'nara prefecture, japan',
  'narino, colombia',
  'national capital district, papua new guinea',
  'national district, dominican republic',
  'nauru',
  'navarra, spain',
  'navarre, spain',
  'nayarit, mexico',
  'neamț county, romania',
  'nebraska, us',
  'negeri sembilan, malaysia',
  'nelson, new zealand',
  'nenetskiy, russia',
  'nepal',
  'netherlands',
  'neuquen, argentina',
  'neuquén, argentina',
  'nevada, us',
  'new brunswick, canada',
  'new caledonia',
  'new hampshire, us',
  'new jersey, us',
  'new mexico, us',
  'new providence, the bahamas',
  'new south wales, australia',
  'new territories, hong kong',
  'new york, us',
  'new zealand',
  'newfoundland and labrador, canada',
  'nghe an, vietnam',
  'niamey, niger',
  'nicaragua',
  'nidwalden, switzerland',
  'niedersachsen, germany',
  'niederösterreich, austria',
  'niger',
  'nigeria',
  'niigata prefecture, japan',
  'ningxia, china',
  'ninh bình province, vietnam',
  'nitra region, slovakia',
  'nizhegorodskaya oblast\', russia',
  'nizhny novgorod oblast, russia',
  'nonthaburi, thailand',
  'noord-brabant, netherlands',
  'noord-holland, netherlands',
  'nord-pas-de-calais picardie, france',
  'nord-pas-de-calais, france',
  'nord-pas-de-calais-picardie, france',
  'nord-trondelag, norway',
  'nord-trøndelag, norway',
  'nordland, norway',
  'nordrhein-westfalen, germany',
  'normandie, france',
  'normandy, france',
  'norrbotten county, sweden',
  'north brabant, netherlands',
  'north carolina, us',
  'north dakota, us',
  'north denmark region, denmark',
  'north district, israel',
  'north holland, netherlands',
  'north karelia, finland',
  'north maluku, indonesia',
  'north ossetia–alania, russia',
  'north rhine-westphalia, germany',
  'north santander, colombia',
  'north sulawesi, indonesia',
  'north sumatra, indonesia',
  'north west, south africa',
  'northeast, iceland',
  'northern borders province, saudi arabia',
  'northern cape, south africa',
  'northern ireland, united kingdom',
  'northern mariana islands',
  'northern mindanao, philippines',
  'northern ostrobothnia, finland',
  'northern region, uganda',
  'northern territory, australia',
  'northern, ghana',
  'northland, new zealand',
  'northwest territories, canada',
  'norway',
  'nova scotia, canada',
  'novgorod oblast, russia',
  'novgorodskaya oblast\', russia',
  'novo mesto, slovenia',
  'novosibirsk oblast, russia',
  'novosibirskaya oblast\', russia',
  'nuevo leon, mexico',
  'nuevo león, mexico',
  'nunavut, canada',
  'oaxaca, mexico',
  'oberösterreich, austria',
  'odessa oblast, ukraine',
  'odisha, india',
  'offaly, ireland',
  'ogun state, nigeria',
  'ohio, us',
  'oita prefecture, japan',
  'okayama prefecture, japan',
  'okinawa prefecture, japan',
  'oklahoma, us',
  'olomouc region, czech republic',
  'olt county, romania',
  'oman',
  'omsk oblast, russia',
  'omskaya oblast\', russia',
  'ondo, nigeria',
  'ontario, canada',
  'opole voivodeship, poland',
  'oppland, norway',
  'oregon, us',
  'orellana, ecuador',
  'orenburg oblast, russia',
  'orenburgskaya oblast\', russia',
  'oriental, morocco',
  'orlovskaya oblast\', russia',
  'oromia, ethiopia',
  'oryol oblast, russia',
  'osaka prefecture, japan',
  'oslo, norway',
  'osmaniye, turkey',
  'ostfold, norway',
  'osun, nigeria',
  'otago, new zealand',
  'ouargla, algeria',
  'overijssel, netherlands',
  'oyo, nigeria',
  'pahang, malaysia',
  'pakistan',
  'palau, us',
  'panama',
  'panama, panama',
  'panamá, panama',
  'pando department, bolivia',
  'panevėžys county, lithuania',
  'papua new guinea',
  'papua, indonesia',
  'paraguay',
  'paraná, brazil',
  'paraíba, brazil',
  'pardubice region, czech republic',
  'parròquia d\'andorra la vella, andorra',
  'parvan, afghanistan',
  'pará, brazil',
  'pasco, peru',
  'pays de la loire, france',
  'país vasco, spain',
  'peloponnisos dytiki ellada ke ionio, greece',
  'penang, malaysia',
  'pennsylvania, us',
  'penza oblast, russia',
  'penzenskaya oblast\', russia',
  'perak, malaysia',
  'perm krai, russia',
  'permskiy kray, russia',
  'pernambuco, brazil',
  'pernik, bulgaria',
  'peru',
  'pest county, hungary',
  'phang-nga, thailand',
  'phetchabun, thailand',
  'phetchaburi, thailand',
  'philippines',
  'phitsanulok, thailand',
  'phnom penh, cambodia',
  'phra nakhon si ayutthaya, thailand',
  'phuket, thailand',
  'piauí, brazil',
  'picardy, france',
  'pichincha, ecuador',
  'piedmont, italy',
  'piemonte, italy',
  'pirkanmaa, finland',
  'piura, peru',
  'plaines wilhems, mauritius',
  'plateau, nigeria',
  'pleven province, bulgaria',
  'plovdiv province, bulgaria',
  'plzeň region, czech republic',
  'podkarpackie voivodeship, poland',
  'podlaskie voivodeship, poland',
  'podlaskie, poland',
  'poitou-charentes, france',
  'poland',
  'poltavs\'ka oblast, ukraine',
  'pomeranian voivodeship, poland',
  'pomorskie, poland',
  'ponce, puerto rico',
  'port of spain, trinidad and tobago',
  'port said governorate, egypt',
  'portalegre district, portugal',
  'portalegre, portugal',
  'porto district, portugal',
  'portugal',
  'portuguesa, venezuela',
  'pr, us',
  'prachuap khiri khan, thailand',
  'prague, czech republic',
  'prahova, romania',
  'preah sihanouk, cambodia',
  'prešov region, slovakia',
  'primorje-gorski kotar county, croatia',
  'primorskiy kray, russia',
  'primorsky krai, russia',
  'prince edward island, canada',
  'principado de asturias, spain',
  'provence-alpes-côte d\'azur, france',
  'pskov oblast, russia',
  'pskovskaya oblast\', russia',
  'puducherry, india',
  'puebla, mexico',
  'puerto plata, dominican republic',
  'puerto rico',
  'puerto rico, us',
  'puglia, italy',
  'punjab, india',
  'punjab, pakistan',
  'puno, peru',
  'puntarenas, costa rica',
  'putrajaya, malaysia',
  'putumayo, colombia',
  'qatar',
  'qena governorate, egypt',
  'qinghai, china',
  'quebec, canada',
  'quebradillas, puerto rico',
  'queensland, australia',
  'querétaro, mexico',
  'quindio, colombia',
  'quintana roo, mexico',
  'québec, canada',
  'rabat-sale-zemmour-zaer, morocco',
  'rabat-salé-zemmour-zaër, morocco',
  'rajasthan, india',
  'rajshahi division, bangladesh',
  'rangpur division, bangladesh',
  'ras al khaimah, united arab emirates',
  'ratchaburi, thailand',
  'razgrad, bulgaria',
  'red sea governorate, egypt',
  'region of murcia, spain',
  'region syddanmark, denmark',
  'region xii, philippines',
  'region zealand, denmark',
  'región de murcia, spain',
  'republic of bashkortostan, russia',
  'republic of indonesia',
  'republic of karelia, russia',
  'republic of khakassia, russia',
  'republic of the congo',
  'republic of the union of myanmar',
  'respublika adygeya, russia',
  'respublika bashkortostan, russia',
  'respublika kalmykiya, russia',
  'respublika mariy el, russia',
  'respublika mordoviya, russia',
  'respublika severnaya osetiya-alaniya, russia',
  'respublika tatarstan, russia',
  'reunion',
  'rheinland-pfalz, germany',
  'rhineland-palatinate, germany',
  'rhode island, us',
  'rhone-alpes, france',
  'rhône-alpes, france',
  'riau islands, indonesia',
  'riau, indonesia',
  'riga, latvia',
  'rio grande do norte, brazil',
  'rio grande do sul, brazil',
  'risaralda, colombia',
  'rivers, nigeria',
  'rivnens\'ka oblast, ukraine',
  'riyadh province, saudi arabia',
  'rogaland, norway',
  'roja municipality, latvia',
  'romania',
  'rondônia, brazil',
  'roraima, brazil',
  'roscommon, ireland',
  'rostov oblast, russia',
  'rostovskaya oblast\', russia',
  'ruse, bulgaria',
  'russia',
  'rwanda',
  'ryazan oblast, russia',
  'ryazanskaya oblast\', russia',
  'région wallonne, belgium',
  'río negro, argentina',
  'rīgas pilsēta, latvia',
  'sa kaeo, thailand',
  'saarland, germany',
  'sabah, malaysia',
  'sacatepequez, guatemala',
  'sachsen, germany',
  'sachsen-anhalt, germany',
  'saga prefecture, japan',
  'saint catherine parish, jamaica',
  'saint george basseterre parish, saint kitts and nevis',
  'saint james parish, jamaica',
  'saint james, barbados',
  'saint kitts and nevis',
  'saint laurent du maroni, french guiana',
  'saint mary parish, jamaica',
  'saint petersburg, russia',
  'saint thomas lowland parish, saint kitts and nevis',
  'saint-paul, reunion',
  'saipan, northern mariana islands',
  'saitama prefecture, japan',
  'saitama-ken, japan',
  'sakarya, turkey',
  'sakha (yakutiya) republits, russia',
  'sakha republic, russia',
  'sakhalin oblast, russia',
  'sakhalinskaya oblast\', russia',
  'sakon nakhon, thailand',
  'salta province, argentina',
  'salzburg, austria',
  'samara oblast, russia',
  'samarskaya oblast\', russia',
  'samoa',
  'samsun, turkey',
  'samut prakan, thailand',
  'san andrés y providencia, colombia',
  'san cristobal, dominican republic',
  'san germán, puerto rico',
  'san jose, costa rica',
  'san josé, costa rica',
  'san josé, uruguay',
  'san juan province, argentina',
  'san juan, puerto rico',
  'san luis potosi, mexico',
  'san luis potosí, mexico',
  'san luis province, argentina',
  'san marcos department, guatemala',
  'san martin, peru',
  'san pedro de macoris, dominican republic',
  'san salvador, el salvador',
  'sandys, bermuda',
  'sankt gallen, switzerland',
  'santa catarina, brazil',
  'santa cruz province, argentina',
  'santa cruz, bolivia',
  'santa fe province, argentina',
  'santa fe, argentina',
  'santander department, colombia',
  'santander, colombia',
  'santarém district, portugal',
  'santarém, portugal',
  'santiago del estero province, argentina',
  'santiago metropolitan region, chile',
  'santiago, dominican republic',
  'santo domingo, dominican republic',
  'saratov oblast, russia',
  'saratovskaya oblast\', russia',
  'sarawak, malaysia',
  'sardegna, italy',
  'sardinia, italy',
  'saskatchewan, canada',
  'satakunta, finland',
  'satu mare county, romania',
  'saudi arabia',
  'saxony, germany',
  'saxony-anhalt, germany',
  'schaan, liechtenstein',
  'schleswig-holstein, germany',
  'scotland, united kingdom',
  'selangor, malaysia',
  'semnan, iran',
  'senegal',
  'serbia',
  'sergipe, brazil',
  'setif, algeria',
  'setubal, portugal',
  'setúbal, portugal',
  'seychelles',
  'shaanxi, china',
  'shandong, china',
  'shanghai shi, china',
  'shanghai, china',
  'shanxi, china',
  'sharjah, united arab emirates',
  'shiga prefecture, japan',
  'shimane prefecture, japan',
  'shinyanga, tanzania',
  'shizuoka prefecture, japan',
  'sibiu, romania',
  'sichuan, china',
  'sicilia, italy',
  'sicily, italy',
  'siem reap, cambodia',
  'sierra leone',
  'siirt, turkey',
  'silesian voivodeship, poland',
  'silistra, bulgaria',
  'sinaloa, mexico',
  'sindh, pakistan',
  'singapore',
  'singida, tanzania',
  'skane county, sweden',
  'skopje, macedonia (fyrom)',
  'skåne county, sweden',
  'sligo, ireland',
  'sliven province, bulgaria',
  'slovakia',
  'slovenia',
  'smolensk oblast, russia',
  'smolenskaya oblast\', russia',
  'smoljan, bulgaria',
  'sofia city province, bulgaria',
  'sofia province, bulgaria',
  'sofia-city, bulgaria',
  'sogn og fjordane, norway',
  'sokoto, nigeria',
  'solomon islands',
  'somalia',
  'somogy county, hungary',
  'songkhla, thailand',
  'sonora, mexico',
  'sor-trondelag, norway',
  'souss-massa-draa, morocco',
  'south africa',
  'south australia, australia',
  'south bohemian region, czech republic',
  'south carolina, us',
  'south dakota, us',
  'south district, israel',
  'south east sulawesi, indonesia',
  'south holland, netherlands',
  'south korea',
  'south moravian region, czech republic',
  'south sinai governorate, egypt',
  'south sudan',
  'south sulawesi, indonesia',
  'south sumatra, indonesia',
  'south-east, botswana',
  'southern nations, nationalities, and people\'s region, ethiopia',
  'southern ostrobothnia, finland',
  'southland, new zealand',
  'spain',
  'special capital region of jakarta, indonesia',
  'special capital region of jakarta, republic of indonesia',
  'special region of yogyakarta, indonesia',
  'split-dalmatia county, croatia',
  'sri lanka',
  'st helier, jersey',
  'st. croix, u.s. virgin islands',
  'st. gallen, switzerland',
  'stara zagora, bulgaria',
  'state of bahia, brazil',
  'state of ceará, brazil',
  'state of espírito santo, brazil',
  'state of goiás, brazil',
  'state of mexico, mexico',
  'state of minas gerais, brazil',
  'state of paraná, brazil',
  'state of pernambuco, brazil',
  'state of rio de janeiro, brazil',
  'state of rio grande do sul, brazil',
  'state of rondônia, brazil',
  'state of santa catarina, brazil',
  'state of são paulo, brazil',
  'stavropol krai, russia',
  'stavropolskiy kray, russia',
  'steiermark, austria',
  'stockholm county, sweden',
  'stockholms län, sweden',
  'styria, austria',
  'suceava county, romania',
  'sucre, colombia',
  'sudan',
  'suez governorate, egypt',
  'sulawesi selatan, indonesia',
  'sums\'ka oblast, ukraine',
  'suphan buri, thailand',
  'surat thani, thailand',
  'suriname',
  'sverdlovsk oblast, russia',
  'sverdlovskaya oblast\', russia',
  'swaziland',
  'sweden',
  'swietokrzyskie, poland',
  'switzerland',
  'syria',
  'szabolcs-szatmár-bereg, hungary',
  'södermanland county, sweden',
  'sør-trøndelag, norway',
  'sălaj, romania',
  'tabasco, mexico',
  'tacna, peru',
  'taiwan',
  'taiwan province, taiwan',
  'tajikistan',
  'takhar, afghanistan',
  'tamaulipas, mexico',
  'tambov oblast, russia',
  'tambovskaya oblast\', russia',
  'tamil nadu, india',
  'tangier-tetouan, morocco',
  'tanzania',
  'taranaki, new zealand',
  'tarija department, bolivia',
  'tartu county, estonia',
  'tashkent province, uzbekistan',
  'tasman, new zealand',
  'tasmania, australia',
  'tatarstan, russia',
  'tbilisi, georgia',
  'tehran, iran',
  'tel aviv district, israel',
  'telangana, india',
  'telemark, norway',
  'teleorman county, romania',
  'telšiai county, lithuania',
  'tennessee, us',
  'terengganu, malaysia',
  'ternopil\'s\'ka oblast, ukraine',
  'tete, mozambique',
  'texas, us',
  'thai binh, vietnam',
  'thai nguyen, vietnam',
  'thailand',
  'the bahamas',
  'thessalia sterea ellada, greece',
  'thua thien hue, vietnam',
  'thurgau, switzerland',
  'thuringia, germany',
  'thüringen, germany',
  'tianjin shi, china',
  'tianjin, china',
  'ticino, switzerland',
  'tien giang, vietnam',
  'tierra del fuego province, argentina',
  'tigray, ethiopia',
  'timiș county, romania',
  'tipperary, ireland',
  'tirol, austria',
  'tizi ouzou, algeria',
  'tiền giang, vietnam',
  'tlaxcala, mexico',
  'toa alta, puerto rico',
  'toa baja, puerto rico',
  'toamasina, madagascar',
  'tocantins, brazil',
  'tochigi prefecture, japan',
  'togo',
  'tokat, turkey',
  'tokushima prefecture, japan',
  'tokyo, japan',
  'tolima, colombia',
  'tolna county, hungary',
  'tombouctou, mali',
  'tomsk oblast, russia',
  'tomskaya oblast\', russia',
  'tonga',
  'toscana, italy',
  'tottori prefecture, japan',
  'toyama prefecture, japan',
  'trabzon, turkey',
  'trentino-alto adige, italy',
  'trentino-alto adige/south tyrol, italy',
  'trenčín region, slovakia',
  'triesen, liechtenstein',
  'trinidad and tobago',
  'trnava region, slovakia',
  'troms, norway',
  'trujillo alto, puerto rico',
  'trujillo, venezuela',
  'tucumán, argentina',
  'tula oblast, russia',
  'tulcea county, romania',
  'tulskaya oblast\', russia',
  'tumbes, peru',
  'tunceli, turkey',
  'tunisia',
  'turkana county, kenya',
  'turkey',
  'turkmenistan',
  'tuscany, italy',
  'tuva, russia',
  'tuyên quang province, vietnam',
  'tver oblast, russia',
  'tverskaya oblast\', russia',
  'tyrol, austria',
  'tyumen oblast, russia',
  'tyumenskaya oblast\', russia',
  'táchira, venezuela',
  'tây ninh province, vietnam',
  'tōkyō-to, japan',
  'u.s. virgin islands',
  'ucayali, peru',
  'udmurt republic, russia',
  'udmurtskaja respublika, russia',
  'udon thani, thailand',
  'uganda',
  'ukraine',
  'ulyanovsk oblast, russia',
  'ulyanovskaya oblast\', russia',
  'umbria, italy',
  'umm al quwain, united arab emirates',
  'united arab emirates',
  'united kingdom',
  'upolu, samoa',
  'upper austria, austria',
  'upper east, ghana',
  'upper normandy, france',
  'upper west, ghana',
  'uppsala county, sweden',
  'uruguay',
  'utah, us',
  'utena county, lithuania',
  'utrecht, netherlands',
  'uttar pradesh, india',
  'uttarakhand, india',
  'utuado, puerto rico',
  'uusimaa, finland',
  'uzbekistan',
  'uşak, turkey',
  'valais, switzerland',
  'valencian community, spain',
  'valle d\'aosta, italy',
  'valle del cauca, colombia',
  'valparaiso region, chile',
  'valverde, dominican republic',
  'van, turkey',
  'vanuatu',
  'varaždinska županija, croatia',
  'varmland county, sweden',
  'varna, bulgaria',
  'vas county, hungary',
  'vaslui county, romania',
  'vaud, switzerland',
  'vega alta, puerto rico',
  'veliko tarnovo province, bulgaria',
  'veneto, italy',
  'venezuela',
  'veracruz, mexico',
  'vermont, us',
  'vest-agder, norway',
  'vestfold, norway',
  'veszprém, hungary',
  'viana do castelo district, portugal',
  'viana do castelo, portugal',
  'vic, australia',
  'victoria, australia',
  'vienna, austria',
  'vientiane prefecture, laos',
  'vietnam',
  'vila real, portugal',
  'vilniaus apskritis, lithuania',
  'vilnius county, lithuania',
  'vinnyts\'ka oblast, ukraine',
  'virgin islands, us',
  'virginia, us',
  'viseu district, portugal',
  'vlaams gewest, belgium',
  'vlaanderen, belgium',
  'vladimir oblast, russia',
  'vladimirskaya oblast\', russia',
  'vojvodina, serbia',
  'volgograd oblast, russia',
  'volgogradskaya oblast\', russia',
  'vologda oblast, russia',
  'vologodskaya oblast\', russia',
  'volta, ghana',
  'volyns\'ka oblast, ukraine',
  'vorarlberg, austria',
  'voronezh oblast, russia',
  'voronezhskaya oblast\', russia',
  'vraca, bulgaria',
  'vrancea county, romania',
  'vysocina region, czech republic',
  'vâlcea county, romania',
  'värmlands län, sweden',
  'västerbotten county, sweden',
  'västernorrland county, sweden',
  'västernorrlands län, sweden',
  'västmanland county, sweden',
  'västra götaland county, sweden',
  'västra götalands län, sweden',
  'waikato, new zealand',
  'wakayama prefecture, japan',
  'wales,',
  'wales, united kingdom',
  'wallis, switzerland',
  'wallonie, belgium',
  'walloon region, belgium',
  'warmian-masurian voivodeship, poland',
  'warmińsko-mazurskie, poland',
  'washington, us',
  'waterford, ireland',
  'wellington, new zealand',
  'west bengal, india',
  'west coast, new zealand',
  'west java, indonesia',
  'west java, republic of indonesia',
  'west kalimantan, indonesia',
  'west nusa tenggara, indonesia',
  'west papua, indonesia',
  'west pomeranian voivodeship, poland',
  'west sumatra, indonesia',
  'west virginia, us',
  'western area, sierra leone',
  'western australia, australia',
  'western cape, south africa',
  'western division, fiji',
  'western province, sri lanka',
  'western sahara',
  'western visayas, philippines',
  'western, ghana',
  'westmeath, ireland',
  'westmoreland parish, jamaica',
  'wexford, ireland',
  'wicklow, ireland',
  'wielkopolskie, poland',
  'wien, austria',
  'wilayah persekutuan kuala lumpur, malaysia',
  'wilayah persekutuan labuan, malaysia',
  'wilayah persekutuan putrajaya, malaysia',
  'wisconsin, us',
  'województwo dolnośląskie, poland',
  'wyoming, us',
  'xinjiang weiwuerzizhiqu, china',
  'xinjiang, china',
  'xizang (tibet), china',
  'yabucoa, puerto rico',
  'yalova province, turkey',
  'yamagata prefecture, japan',
  'yamaguchi prefecture, japan',
  'yamalo-nenets autonomous okrug, russia',
  'yamalo-nenetskiy, russia',
  'yamanashi prefecture, japan',
  'yangon region, myanmar (burma)',
  'yangon region, republic of the union of myanmar',
  'yaracuy, venezuela',
  'yaroslavl oblast, russia',
  'yaroslavskaya oblast\', russia',
  'yauco, puerto rico',
  'yemen',
  'yerevan, armenia',
  'yucatan, mexico',
  'yucatán, mexico',
  'yukon territory, canada',
  'yunnan, china',
  'zabaykalskiy kray, russia',
  'zabaykalsky krai, russia',
  'zacatecas, mexico',
  'zakarpats\'ka oblast, ukraine',
  'zala county, hungary',
  'zambezia province, mozambique',
  'zambia',
  'zamboanga peninsula, philippines',
  'zaporiz\'ka oblast, ukraine',
  'zhejiang sheng, china',
  'zhejiang, china',
  'zhytomyrs\'ka oblast, ukraine',
  'zlin region, czech republic',
  'zuid-holland, netherlands',
  'zulia, venezuela',
  'zurich, switzerland',
  'çankırı, turkey',
  'çorum, turkey',
  'évora district, portugal',
  'évora, portugal',
  'île-de-france, france',
  'örebro county, sweden',
  'östergötland county, sweden',
  'östergötlands län, sweden',
  'østfold, norway',
  'ústí nad labem region, czech republic',
  'łódź voivodeship, poland',
  'śląskie, poland',
  'şanlıurfa province, turkey',
  'şanlıurfa, turkey',
  'şırnak, turkey',
  'šiauliai county, lithuania',
  'žilina region, slovakia',
  'الريان, qatar',
  'จังหวัด กรุงเทพมหานคร, thailand',
  'ชัยภูมิ, thailand',
]);
// Total: 1856 values
